### ISSUE TITLE
Composer scripts failing (post-install-cmd)

### ISSUE THREAD

**Issue by bretmette** [mkenney/docker-composer#2] opened 2016-10-06 17:57 UTC
I have been trying to work this one out for a little bit now and decided it's worth making a proper issue about.

This is on a laravel 5.2.45 setup. Happens pretty much any time I run composer with laravel.

```
bmette$ composer require endroid/qrcode
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.7 for endroid/qrcode
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/options-resolver (v3.1.5)
    Downloading: 100%         

  - Installing endroid/qrcode (1.7.4)
    Downloading: 100%         

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /src/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /src/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('log')
#4 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminat in /src/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
Script php artisan optimize handling the post-update-cmd event returned with error code 255

Installation failed, reverting ./composer.json to its original content.
```

Using the alpine version

```
TAG=php7
BRANCH=master
```

I believe this error is a bit misleading, what is really happening is an error is occurring before the logger is loaded and it's throwing that error instead of the actual error. If I can get to the PHP logs I can see exactly what is going on.

I am trying to grab the PHP logs on the container but I can't find anything. Any idea where they are stored?

As a work around I can run composer with `--no-scripts` and then run the scripts after install. I would like to get a proper fix in place though.

**Comment by mkenney** [comment] 2016-10-06 21:01
Hey @bretmette,

The `Do not run Composer as root/super user!` message makes me think you may be using an older image, can you run `docker pull mkenney/composer:php7` and give it another try?

Here's what I got when I tried:

```
→ composer self-update
Trying to pull repository docker.io/mkenney/composer ...
php7: Pulling from docker.io/mkenney/composer
c0cb142e4345: Already exists
af6b8c8dbfda: Pull complete
594ac21fa78f: Pull complete
Digest: sha256:467e583c08b3c7837cf563a7093a78f8b4697fb65ac338b9823f55c98f6fd1aa
Status: Downloaded newer image for docker.io/mkenney/composer:php7
2016-10-06 14:55:11 URL:https://raw.githubusercontent.com/mkenney/docker-composer/master/bin/composer [322/322] -> "/home/mkenney/bin/composer" [1]

→ composer require endroid/qrcode
Using version ^1.7 for endroid/qrcode
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/options-resolver (v3.1.5)
    Downloading: 100%

  - Installing endroid/qrcode (1.7.4)
    Downloading: 100%

Writing lock file
Generating autoload files
```

Let me know if that fixes the issue, if not I'll dig in further. Thanks!

**Comment by bretmette** [comment] 2016-10-07 19:43
@mkenney I think it may be related to OS X specifically. I am still getting the "no root" warning so I am wondering if it is related to the [bower problem with a similar message](https://github.com/mkenney/docker-npm/issues/4).

```
bmette$ docker pull mkenney/composer:php7
php7: Pulling from mkenney/composer

c0cb142e4345: Pull complete 
af6b8c8dbfda: Pull complete 
594ac21fa78f: Pull complete 
Digest: sha256:467e583c08b3c7837cf563a7093a78f8b4697fb65ac338b9823f55c98f6fd1aa
```

```
bmette$ composer require endroid/qrcode
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.7 for endroid/qrcode
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/options-resolver (v3.1.5)
    Downloading: 100%         

  - Installing endroid/qrcode (1.7.4)
    Downloading: 100%         

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /src/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /src/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('log')
#4 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /src/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminat in /src/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
Script php artisan optimize handling the post-update-cmd event returned with error code 255

Installation failed, reverting ./composer.json to its original content.
```

**Comment by mkenney** [comment] 2016-10-08 04:12
Yeah, that's very strange. How are you running docker on your Mac?

I can't reproduce it on my Mac either (that was on a CentOS box), but you're running newer versions than me

```
→ uname -a
Darwin rpco-mkenne1410.local 13.4.0 Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin

→ docker -v
Docker version 1.9.0, build 76d6bc9

→ docker images | grep composer
mkenney/composer                                             php7                sha256:98922        7 days ago          96.28 MB

→ composer require endroid/qrcode
Using version ^1.7 for endroid/qrcode
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/options-resolver (v3.1.5)
    Downloading: 100%

  - Installing endroid/qrcode (1.7.4)
    Downloading: 100%

Writing lock file
Generating autoload files
```

**Comment by mkenney** [comment] 2016-10-08 04:12
Didn't mean to close this.

When the image writes out files to the vendor folder, are they owned by root?

**Comment by bretmette** [comment] 2016-10-08 04:36
```
bmette$ uname -a
Darwin Bret-Mettes-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Aug 29 21:14:16 PDT 2016; root:xnu-2782.50.6~1/RELEASE_X86_64 x86_64

bmette$ docker -v
Docker version 1.12.1, build 6f9534c

bmette$ docker images | grep composer
mkenney/composer    php7                989220d271a4        7 days ago          96.28 MB
mkenney/composer    <none>              a5e203d1a91d        4 weeks ago         96.26 MB
```

**Comment by bretmette** [comment] 2016-10-08 04:37
> When the image writes out files to the vendor folder, are they owned by root?

No, owned by the user that executes composer.

I noticed I have a second composer image, I'll try removing the older one and see if that changes anything.

**Comment by mkenney** [comment] 2017-02-17 23:33
No activity, closing

**Closed as completed by mkenney** 2017-02-17 23:33 UTC
